version: '3.7'

services:
    phoneinfoga:
      container_name: phoneinfoga
      restart: unless-stopped
      image: sundowndev/phoneinfoga:latest
      exspose:
        - "5000"
      env_file:
      - env_file_integrations
      environment:
      - GIN_MODE=release